### ISSUE TITLE
%RELEASE_COUNTRY% wiped out / not written

### ISSUE THREAD

**Issue by adriaon** [ghDaYuYu/foo_discogger#118] opened 2024-09-15 13:55 UTC
Hi,

Recent releases, including 1.0.21.beta.2, wipe out or do not write %RELEASE_COUNTRY%. I've seen this for various releases. One of them is 315802.

Cheers,
Adriaaan.

**Comment by ghuDaYuYu** [comment] 2024-09-15 18:28
Hello Adriaaan,
Can´t replicate here, RELEASE_COUNTRY was tagged correctly using 315802.
It will help troubleshoot having a look at the preview stats ('show stats' option).
There should be a line for DISCOGS_COUNTRY, showing its value and whether is going to be written, updated, skipped, or 
Regards!

**Comment by adriaon** [comment] 2024-09-15 19:46
Hi,

I checked again, and it still fails here. I'm using Fb 32bit 2.2 9/11.

![image](https://github.com/user-attachments/assets/62ba3c10-2f90-460d-933d-e585b0bbf519)
![image](https://github.com/user-attachments/assets/78412787-52ad-4b9d-b610-753e4792daf6)
![image](https://github.com/user-attachments/assets/230359d5-aa1a-4e42-92a5-45ddcf8c8fa2)

I tried with removing all tags first, but that gives the same result.

Cheers, Adriaan.

**Comment by ghuDaYuYu** [comment] 2024-09-15 20:34
Hello Adriaan,
Thanks for the screenshot.
Would you try enlarging the statistics columns (Write - Update - Skip - Equal) and post  a new screenshot?
What action is set to the DISCOGS_COUNTRY tag in the tag mapping panel?

**Comment by adriaon** [comment] 2024-09-15 21:07
This is the mapping:
![image](https://github.com/user-attachments/assets/2782bfa8-e41d-4680-8a8f-f221fdf3083e)
I wasn't aware of those columns. Here you go:
![image](https://github.com/user-attachments/assets/3265a181-8d52-4028-863c-16347436d6f1)

Cheers, Adriaan.

**Comment by adriaon** [comment] 2024-09-15 21:45
I tried the 64 bit version and that is working just fine......

**Comment by ghuDaYuYu** [comment] 2024-09-15 22:04
My test with fb2k 32bit was also ok.
I was checking the release history at Discogs. Trying to figure out if the country was updated lately.
I would say that your local cached release has an empty value, in that 32bit 2.2 9/11 installation.
The next test would be either to disable the disk cache and restart foobar 2000, or manually delete the cache folder for release 315802. It should be located here: `<profile>\foo_discogger-cache\artists\194\release\315802`

**Comment by adriaon** [comment] 2024-09-15 22:14
I have diskcache disabled (and deleted). Also cleared to mem cache. No difference.

**Comment by ghuDaYuYu** [comment] 2024-09-15 22:19
Would deleting the DISCOGS_COUNTRY tag, and adding it again make any difference?
(In the Tag mapping panel, button Add tag... > Label > Discogs Country)

**Comment by adriaon** [comment] 2024-09-15 22:25
Unfortunately, no difference...

**Comment by ghuDaYuYu** [comment] 2024-09-15 22:29
This is a nice one : )
I am wondering how I could replicate the bug here.

**Comment by adriaon** [comment] 2024-09-15 22:34
I just tried with the restored defaults. Also no difference...

**Comment by ghuDaYuYu** [comment] 2024-09-15 22:40
I am still unsure about the release data.
If you are still keen on continue troubleshooting, just to be 100% sure, that 'UK' is there, you could enable disk cache, delete memory cache and reload the release, then edit <profile>\foo_discogger-cache\artists\194\release\315802\root.json and search for 'country'
it should look like:
... , "country": "UK", "released": "2004-03-00", ...

**Comment by adriaon** [comment] 2024-09-15 22:54
I could only find ..\foo_discogger-cache\artists\220767\release\315802 in the 32 bit cache. And that has a "country": "UK" entry. Oddly, artists\622 is in the 64 bit cache, but without a releases folder.

**Comment by ghuDaYuYu** [comment] 2024-09-16 11:30
The cache assigned the release to artist 220767 in the 32 bit cache. That is fine, it could have been assigned to 194 or to any other artist from that VA release, depending on the 'Write tag...' sequence. The same also applies to the 64 bit cache. The lack of releases for artist 622 suggests that they were not needed. That is also expected behavior.
I am sorry it is taking so long to troubleshoot this issue... it is getting also laborious.
If you do not mind, I would suggest backing up the configuration files ...

- Open Notepad, copy and paste both the OAuth token and secret
- Close foobar 2000
- Backup `foo_discogger.dll.cfg` and `foo_vbookmark.dll.dat` from `<profile>\configuration` to a folder of your choice.
- Delete `foo_discogger.dll.cfg` from `<profile>\configuration` to a folder of your choice.

Reopen foobar 2000, paste the OAuth token and secret.
Does the test still fail, is 315802 DISCOGS_COUNTRY also empty?

**Comment by adriaon** [comment] 2024-09-16 15:44
I had already tried to backup the mappings, remove them all and import them again. That didn't help.
I don't have a foo_vbookmark.dll.dat, but otherwise it worked and the country tag is written now. 
Even after deleting all mappings and importing them from yesterdays export it still works.
Would you appreciate to have my backed up foo_discogger.dll.cfg for analyses?
Thanks for your help. Cheers, Adriaan.

**Comment by ghuDaYuYu** [comment] 2024-09-19 04:30
I believe that '32 bit installation' and 'missing foo_vbookmark.dll.dat' may provide some hints if the issue is raised again.
Unfortunately, the configuration file did not help much. I get same expected 'UK' value using it.
I believe we should close the issue for now as 'solved and unreplicable'. 
Thanks for your feedback!

**Closed by ghuDaYuYu** 2024-09-19 04:30 UTC
